// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAddressInfo = "address_info"

// AddressInfo 全国城市信息表
type AddressInfo struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Pid       int32     `gorm:"column:pid;not null" json:"pid"`
	Status    int32     `gorm:"column:status;not null" json:"status"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName AddressInfo's table name
func (*AddressInfo) TableName() string {
	return TableNameAddressInfo
}
