// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminInfo = "admin_info"

// AdminInfo mapped from table <admin_info>
type AdminInfo struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null;comment:用户名" json:"name"`           // 用户名
	Password  string    `gorm:"column:password;not null;comment:密码" json:"password"`    // 密码
	RoleIds   string    `gorm:"column:role_ids;not null;comment:角色ids" json:"role_ids"` // 角色ids
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	UserSalt  string    `gorm:"column:user_salt;not null;comment:加密盐" json:"user_salt"`   // 加密盐
	IsAdmin   bool      `gorm:"column:is_admin;not null;comment:是否超级管理员" json:"is_admin"` // 是否超级管理员
}

// TableName AdminInfo's table name
func (*AdminInfo) TableName() string {
	return TableNameAdminInfo
}
