// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCartInfo = "cart_info"

// CartInfo mapped from table <cart_info>
type CartInfo struct {
	ID             int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:购物车表" json:"id"` // 购物车表
	UserID         int32          `gorm:"column:user_id;not null" json:"user_id"`
	GoodsOptionsID int32          `gorm:"column:goods_options_id;not null;comment:商品规格id" json:"goods_options_id"` // 商品规格id
	Count          int32          `gorm:"column:count;not null;comment:商品数量" json:"count"`                         // 商品数量
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CartInfo's table name
func (*CartInfo) TableName() string {
	return TableNameCartInfo
}
