// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCommentInfo = "comment_info"

// CommentInfo mapped from table <comment_info>
type CommentInfo struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID  int32          `gorm:"column:parent_id;not null;comment:父级评论id" json:"parent_id"` // 父级评论id
	UserID    int32          `gorm:"column:user_id;not null" json:"user_id"`
	ObjectID  int32          `gorm:"column:object_id;not null" json:"object_id"`
	Type      bool           `gorm:"column:type;not null;comment:评论类型：1商品 2文章" json:"type"` // 评论类型：1商品 2文章
	Content   string         `gorm:"column:content;not null;comment:评论内容" json:"content"`   // 评论内容
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CommentInfo's table name
func (*CommentInfo) TableName() string {
	return TableNameCommentInfo
}
