// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameConsigneeInfo = "consignee_info"

// ConsigneeInfo mapped from table <consignee_info>
type ConsigneeInfo struct {
	ID     int32 `gorm:"column:id;primaryKey;autoIncrement:true;comment:收货地址表" json:"id"` // 收货地址表
	UserID int32 `gorm:"column:user_id;not null" json:"user_id"`
	/*
		默认地址1  非默认0

	*/
	IsDefault bool           `gorm:"column:is_default;not null;comment:默认地址1  非默认0\n" json:"is_default"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Phone     string         `gorm:"column:phone;not null" json:"phone"`
	Province  string         `gorm:"column:province;not null" json:"province"`
	City      string         `gorm:"column:city;not null" json:"city"`
	Town      string         `gorm:"column:town;not null;comment:县区" json:"town"`       // 县区
	Street    string         `gorm:"column:street;not null;comment:街道乡镇" json:"street"` // 街道乡镇
	Detail    string         `gorm:"column:detail;not null;comment:地址详情" json:"detail"` // 地址详情
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName ConsigneeInfo's table name
func (*ConsigneeInfo) TableName() string {
	return TableNameConsigneeInfo
}
