// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCouponInfo = "coupon_info"

// CouponInfo 轮播图表

type CouponInfo struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
	/*
		优惠前面值 单位分

	*/
	Price      int32          `gorm:"column:price;not null;comment:优惠前面值 单位分\n" json:"price"`
	GoodsIds   string         `gorm:"column:goods_ids;not null;comment:关联使用的goods_ids  逗号分隔" json:"goods_ids"` // 关联使用的goods_ids  逗号分隔
	CategoryID int32          `gorm:"column:category_id;not null;comment:关联使用的分类id" json:"category_id"`        // 关联使用的分类id
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CouponInfo's table name
func (*CouponInfo) TableName() string {
	return TableNameCouponInfo
}
