// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileInfo = "file_info"

// FileInfo mapped from table <file_info>
type FileInfo struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null;comment:图片名称" json:"name"`       // 图片名称
	Src       string    `gorm:"column:src;not null;comment:本地文件存储路径" json:"src"`     // 本地文件存储路径
	URL       string    `gorm:"column:url;not null;comment:URL地址" json:"url"`        // URL地址
	UserID    int32     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"` // 用户id
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName FileInfo's table name
func (*FileInfo) TableName() string {
	return TableNameFileInfo
}
