// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGoodsOptionsInfo = "goods_options_info"

// GoodsOptionsInfo 商品规格表

type GoodsOptionsInfo struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GoodsID   int32          `gorm:"column:goods_id;not null;comment:商品id" json:"goods_id"`       // 商品id
	PicURL    string         `gorm:"column:pic_url;not null;comment:图片" json:"pic_url"`           // 图片
	Name      string         `gorm:"column:name;not null;comment:商品名称" json:"name"`               // 商品名称
	Price     int32          `gorm:"column:price;not null;default:1;comment:价格 单位分" json:"price"` // 价格 单位分
	Stock     int32          `gorm:"column:stock;not null;comment:库存" json:"stock"`               // 库存
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName GoodsOptionsInfo's table name
func (*GoodsOptionsInfo) TableName() string {
	return TableNameGoodsOptionsInfo
}
