// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderGoodsInfo = "order_goods_info"

// OrderGoodsInfo 文章（种草）表
type OrderGoodsInfo struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:商品维度的订单表" json:"id"`    // 商品维度的订单表
	OrderID        int32     `gorm:"column:order_id;not null;comment:关联的主订单表" json:"order_id"`              // 关联的主订单表
	GoodsID        int32     `gorm:"column:goods_id;not null;comment:商品id" json:"goods_id"`                 // 商品id
	GoodsOptionsID int32     `gorm:"column:goods_options_id;comment:商品规格id sku id" json:"goods_options_id"` // 商品规格id sku id
	Count          int32     `gorm:"column:count;not null;comment:商品数量" json:"count"`                       // 商品数量
	Remark         string    `gorm:"column:remark;not null;comment:备注" json:"remark"`                       // 备注
	Price          int32     `gorm:"column:price;not null;comment:订单金额 单位分" json:"price"`                   // 订单金额 单位分
	CouponPrice    int32     `gorm:"column:coupon_price;not null;comment:优惠券金额 单位分" json:"coupon_price"`    // 优惠券金额 单位分
	ActualPrice    int32     `gorm:"column:actual_price;not null;comment:实际支付金额 单位分" json:"actual_price"`   // 实际支付金额 单位分
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName OrderGoodsInfo's table name
func (*OrderGoodsInfo) TableName() string {
	return TableNameOrderGoodsInfo
}
