// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePermissionInfo = "permission_info"

// PermissionInfo mapped from table <permission_info>
type PermissionInfo struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;not null;comment:权限名称" json:"name"` // 权限名称
	Path      string         `gorm:"column:path;not null;comment:路径" json:"path"`   // 路径
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName PermissionInfo's table name
func (*PermissionInfo) TableName() string {
	return TableNamePermissionInfo
}
