// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRefundInfo = "refund_info"

// RefundInfo mapped from table <refund_info>
type RefundInfo struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:售后退款表" json:"id"` // 售后退款表
	Number  string `gorm:"column:number;not null;comment:售后订单号" json:"number"`              // 售后订单号
	OrderID int32  `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`           // 订单id
	/*
		要售后的商品id

	*/
	GoodsID int32  `gorm:"column:goods_id;not null;comment:要售后的商品id\n" json:"goods_id"`
	Reason  string `gorm:"column:reason;not null;comment:退款原因" json:"reason"` // 退款原因
	/*
		状态 1待处理 2同意退款 3拒绝退款

	*/
	Status    bool           `gorm:"column:status;not null;default:1;comment:状态 1待处理 2同意退款 3拒绝退款\n" json:"status"`
	UserID    int32          `gorm:"column:user_id;not null;comment:用户id" json:"user_id"` // 用户id
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName RefundInfo's table name
func (*RefundInfo) TableName() string {
	return TableNameRefundInfo
}
