// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRolePermissionInfo = "role_permission_info"

// RolePermissionInfo mapped from table <role_permission_info>
type RolePermissionInfo struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID       int32     `gorm:"column:role_id;not null;comment:角色id" json:"role_id"`             // 角色id
	PermissionID int32     `gorm:"column:permission_id;not null;comment:权限id" json:"permission_id"` // 权限id
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName RolePermissionInfo's table name
func (*RolePermissionInfo) TableName() string {
	return TableNameRolePermissionInfo
}
