// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoleInfo = "role_info"

// RoleInfo mapped from table <role_info>
type RoleInfo struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;not null;comment:角色名称" json:"name"` // 角色名称
	Desc      string         `gorm:"column:desc;not null;comment:描述" json:"desc"`   // 描述
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName RoleInfo's table name
func (*RoleInfo) TableName() string {
	return TableNameRoleInfo
}
