// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserCouponInfo = "user_coupon_info"

// UserCouponInfo mapped from table <user_coupon_info>
type UserCouponInfo struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户优惠券表" json:"id"` // 用户优惠券表
	UserID    int32          `gorm:"column:user_id;not null" json:"user_id"`
	CouponID  int32          `gorm:"column:coupon_id;not null" json:"coupon_id"`
	Status    bool           `gorm:"column:status;not null;default:1;comment:状态：1可用 2已用 3过期" json:"status"` // 状态：1可用 2已用 3过期
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserCouponInfo's table name
func (*UserCouponInfo) TableName() string {
	return TableNameUserCouponInfo
}
