// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserInfo = "user_info"

// UserInfo 商品表
type UserInfo struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string         `gorm:"column:name;not null;comment:用户名" json:"name"`    // 用户名
	Avatar       string         `gorm:"column:avatar;not null;comment:头像" json:"avatar"` // 头像
	Password     string         `gorm:"column:password;not null" json:"password"`
	UserSalt     string         `gorm:"column:user_salt;not null;comment:加密盐 生成密码用" json:"user_salt"`       // 加密盐 生成密码用
	Sex          bool           `gorm:"column:sex;not null;default:1;comment:1男 2女" json:"sex"`             // 1男 2女
	Status       bool           `gorm:"column:status;not null;default:1;comment:1正常 2拉黑冻结" json:"status"`   // 1正常 2拉黑冻结
	Sign         string         `gorm:"column:sign;not null;comment:个性签名" json:"sign"`                      // 个性签名
	SecretAnswer string         `gorm:"column:secret_answer;not null;comment:密保问题的答案" json:"secret_answer"` // 密保问题的答案
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserInfo's table name
func (*UserInfo) TableName() string {
	return TableNameUserInfo
}
